name: RulesUI
main: RulesUI\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 0.0.1
author: BajanVlogs, OpGamer

commands:
 info:
  description: "This is to learn about the basics of the server!"
